import Link from 'next/link';
import styles from './layout.module.css';

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <header className={styles.header}>
      <div className={styles.logo}><Link href={'/'} className={styles.logo}>E.O.T.</Link></div>
      <nav className={styles.nav}>
        <a href="/">Home</a>
        <a href={'/create-haiku'}>Create</a>
      </nav>
    </header>
        {children}
      </body>
    </html>
  );
}
